### ISSUE TITLE
Implement more Properties in SmtpClient wrapper class

### ISSUE THREAD

**Issue by bacathey** [gavynriebau/System.Net.Mail.Abstractions#1]
Glad to see this out here!
Any reason why you are not implementing properties like Host in the SmtpClient wrapper? It would be nice to have these in order to set things like Host/Post closer to the executing code. I would prefer not to be required to set mailSettings or new up a loaded SmtpClient constructor in my IoC container.

I could work on a do a Pull request... :)

**Comment by gavynriebau** [comment]
I've added more of the properties from System.Net.Mail.SmtpClient.

You can also avoid setting these values in code using a web.config or app.config file and the configuration/system.net/mailSettings/smtp/network element.

``` xml
<configuration>
  <system.net>
    <mailSettings>
      <smtp deliveryMethod="network">
        <network
          host="localhost"
          port="25"
          defaultCredentials="true"
        />
      </smtp>
    </mailSettings>
  </system.net>
</configuration>
```

https://msdn.microsoft.com/en-us/library/w355a94k(v=vs.110).aspx

**Comment by bacathey** [comment]
Perfect! Thanks.
