### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by bburgy** [gavynriebau/System.Net.Mail.Abstractions#3]
Hello,

Thank you for merging my pull request but can you publish the latest version for the .NET Standard instead of the .NET 45?

I think you don't have anymore need to publish the NET45 version by the way.

The following command should work.

`dotnet pack -c Release --include-symbols --include-source`

**Comment by Bidthedog** [comment]
Also need this - getting warnings in VS about the dotnet Standard library using 4.6.1 instead:

```
Package 'System.Net.Mail.Abstractions 1.1.20' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

Upon closer inspection, there is `v1.1.20` (default) and `v1.1.2` - 1.1.2 contains the dotnet standard package, so use that instead for now - until the default 1.1.20 package's manifest has been updated to include dotnet standard.

**Comment by bburgy** [comment]
Ok, thanks.
